# Site settings
title: Michael Nilsson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
	micnil_
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelnilsson.me" # the base hostname & protocol for your site
twitter_username: micnil_
github_username:  micnil

# Build settings
markdown: kramdown
