# Site settings
title: Michael Nilsson
email: michaelnilsson90@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
    Site based on the base Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelnilsson.me" # the base hostname & protocol for your site
twitter_username: micnil_
github_username: micnil

# Build settings
markdown: kramdown
